---
# tasks file for create-launch-configuration
- name: Create Launch Configuration
  ec2_lc:
    region: "{{ region }}"
    name: "{{ lc_name }}"
    image_id: "{{ lc_ami }}"
    key_name: "{{ keypair }}"
    instance_type: "{{ instance_type }}"
    security_groups: "{{ lc_security_groups }}"
    instance_monitoring: "{{ instance_monitoring }}"
    instance_profile_name: "{{ instance_profile_name }}"
    user_data: "{{ lc_user_data }}"
